apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: hello-world
build:
  artifacts:
    - image: gcr.io/hello-world
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/hello-world.yaml